name: Deploy Node Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u hiltonborah123 -p Hilton123@    
      - name: Build Docker Image
        run: docker build -t hiltonborah123/habit-vault-backend  .
      - name: Publish Image to docker hub
        run: docker push hiltonborah123/habit-vault-backend:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull hiltonborah123/habit-vault-backend:latest 
      - name: Delete old container
        run: docker rm -f habit-vault-backend-container  
      - name: Run Docker Container
        run: docker run -d -p 5000:5000 --name habit-vault-backend-container hiltonborah123/habit-vault-backend